#!/usr/bin/env node

const path = require('path'),
      { execSync, spawn } = require('child_process'),
      beta = process.env.BITWIG_VERSION && process.env.BITWIG_VERSION.includes('Beta')

function winenv(name) {
  // Full path cmd.exe for /etc/wsl.conf [interop] appendWindowsPath = false
  return execSync(`/mnt/c/Windows/system32/cmd.exe /C echo %${name}% 2> /dev/null`, {
    stdio: ['pipe', 'pipe', 'ignore']
  }).toString().replace(/[\r\n]+$/g, '')
}

function win2wslpath(winPath) {
  return execSync(`wslpath "${winPath}"`)
    .toString().replace(/[\r\n]+$/g, '')
}
const bitwig = path.join(win2wslpath(winenv('PROGRAMFILES')), 'Bitwig Studio', process.env.BITWIG_VERSION, 'Bitwig Studio.exe')
const childProcess = spawn(bitwig, [], {
  detached: true,
  stdio: 'pipe',
  env: {
    BITWIG_DEBUG_PORT: process.env.BITWIG_DEBUG_PORT,
    WSLENV: 'BITWIG_DEBUG_PORT'
  }
})

childProcess.stdout.on('data', data => {
  process.stdout.write(data)
})

childProcess.stderr.on('data', data => {
  process.stderr.write(data)
})
